#! /usr/bin/env bash

set -e

#module load foss Boost/1.61.0-foss-2016b-Python-2.7.12 BCFtools/1.5-foss-2016b SAMtools/1.5-foss-2016b lxml/3.6.4-foss-2016b-Python-2.7.12 HTSlib/1.5-foss-2016b zlib bzip2 ncurses &> /dev/null


CXX="g++"
CXXFLAGS="-isystem ${EBROOTHTSLIB} -isystem ${BOOST_ROOT} -pedantic -W -Wall -Wno-unknown-pragmas -fno-strict-aliasing -O3 -fno-tree-vectorize -DNDEBUG -D__STDC_LIMIT_MACROS"
LDFLAGS="-L${EBROOTHTSLIB} -L${BOOST_ROOT}/stage/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time -lhts -lz -Wl,-rpath,${EBROOTHTSLIB}"

${CXX} ${CXXFLAGS} src/nRex.cpp -o src/nRex ${LDFLAGS}
